---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Girt with a boyish garb for boyish task,  
   Eager she wields her spade: yet loves as well  
Rest on the friendly knee, intent to ask  
         The tale one loves to tell.  

Rude scoffer of the seething outer strife,  
   Unmeet to read her pure and simple spright,  
Deem, if thou wilt, such hours a waste of life,  
         Empty of all delight!  

Chat on, sweet Maid, and rescue from annoy  
   Hearts that by wiser talk are unbeguilded.  
Ah, happy he who owns the tenderest joy,  
         The heart-love of a child!  

Away, fond thoughts, and vex my soul no more!  
   Work claims my wakeful nights, my busy days,  
Albeit bright memories of the sunlit shore  
         Yet haunt my dreaming gaze.  

